### PR TITLE
Add license and repository metadata to package configuration.

### PR DESCRIPTION
**Pull request by domi41**
> When your are ready to share your code, run the test suite:
> 
>     $ meteor npm run test
>     $ meteor npm run test-app
> 
> and ensure all tests pass.

_Neither pass on my setup,_ but I'm pushing the PR anyway :eyes: 

---

**This PR calls for discussion** ; the supplied repository is over here at github. One could argue that the whole development stack should be as **libre** and **transparent** as reasonably achievable. Code hosting and issue handling is also pretty well done by the libre [gitlab](https://fr.wikipedia.org/wiki/GitLab_CE) and at least [one nonprofit](https://framagit.org/public/projects) host, maintain and run an instance of it for free for open projects such as sovereign.

_This perhaps even calls for polling?_

### CODE REVIEW

**Comment by domi41** [comment]
### **_Thumbs up to switch main development to some instance of gitlab._**

**Comment by domi41** [comment]
### **_Thumbs up to stay on github for a little while._**

**Comment by domi41** [comment]
### _**Thumbs up to stay on github forever.**_

**Comment by santisiri** [comment]
I'm favoring github right now simply for the fact that it enjoys the greatest extent of network effects and for the purpose of putting the word out there, I think we should invest in the community most of the developers hang out right now. That said: I love gitlab and I think we should definitely pursue having a repo there in the future.

**Comment by fredhampton** [comment]
@santisiri What is the current version number of sovereign ?

**Pull request merged**
