### PR TITLE
moved opencollective-postinstall to devDependencies

### PR DESCRIPTION
**Pull request by xdamman**
Fixes https://github.com/OpenCollective/opencollective-postinstall/issues/2

### CODE REVIEW

**Comment by Tsiqxwexwene** [comment]
Hello @xdamman still having a similar problem. Not a programmer but wanted to take look at the app. I have followed the process outlined on Democracy.Earth. 

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\ryans\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.3_2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\ryans\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.3_2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.7.3
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! opencollective-postinstall@1.1.1 postinstall: `node bin/setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencollective-postinstall@1.1.1 postinstall script 'node bin/setup.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencollective-postinstall package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/setup.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencollective-postinstall
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencollective-postinstall
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ryans\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\.npm\_logs\2017-08-20T05_24_17_265Z-debug.log

**Comment by domi41** [comment]
Hello @Tsiqxwexwene , and thanks for the bug report ! I'm having the same issue with `master`, which is not very stable right now for multiple other reasons. If it's just to try out the app, there's a [public node available](http://alpha.democracy.earth). If you really want to try it locally, I've noticed that the `staging` branch was more stable : `git checkout staging`

**Comment by Tsiqxwexwene** [comment]
Thank you. I'll be monitoring with great anticipation. I am the Chief of one of 17 band of the Secwepemc Nation (situated in BC, Canada). Working to rebuild our democratic governance based on principles that existed (including vote delegation; consensus; respectful contention; development and acknowledgement of subject matter experts, gifted persons, acknowledgement of all peoples value of participation in governance)  prior to the devastation colonialism brought. I believe this technology will enable current society to 'catch up' with our previous governance system, and instill in all people a sense of value, purpose and self-determination. Thank you for the work you are doing. Please let me know if there is any way i can contribute. My formal education is in economics and Indigenous Governance. Kukstsemc.

**Comment by herbstephens** [comment]
Hello @Tsiqxwexwene ...Ryan: Thank you for your offer to contribute. Much appreciated..as a non-profit, we can always use the help .. and look for such great applications of our work.

Agree with your sentiments .. ("devastation colonialism brought", etc.) and welcome exploring how we might work together. I have much respect for the First Nations of Canada .. and happy to help with your sovereignty and governance. I am from Michigan .. have spent much time in Canada .. and my brother is Canadian (lives in Squamish, BC).

**Comment by xdamman** [comment]
Can someone with a windows machine try to change the post install in `package.json` from `"./node_modules/.bin/opencollective-postinstall || exit 0"` to simply `"opencollective postinstall"` and report if this works?

Also the dependency can be updated to `"opencollective": "^1.0.3"` (instead of `"opencollective-postinstall"`)

**Comment by Tsiqxwexwene** [comment]
This change did not change the outcome on my windows machine.

**Comment by imdario** [comment]
I found this issue also in Ubuntu 16.04. I applied @xdamman suggestion in his last comment and npm worked fine.

**Pull request merged**
