### PR TITLE
Include another possibility of SC incorporation

### PR DESCRIPTION
**Pull request by vncoelho**
Neo blockchain is suitable for this kind of applications, different aspects of the Neo ecosystem makes it suitable to the interests of this current project.

I suggest considering this possibility and the NeoCompiler Eco(system) for the development of the Smart Contracts.

### CODE REVIEW

**Comment by santisiri** [comment]
Is this related to the $NEO cryptocurrency?

**Comment by vncoelho** [comment]
Perhaps, yes.

Let's say: "digital assets platform"
aheuwhahau

The paradigm of Neo is quite suitable for your application.

We can submmit something for the one of the next Dapps competitions. It may be an interest path towards some funding for deploying the aplication.

Otherwise, we can also check other possibilities.

**Comment by santisiri** [comment]
I'm fine providing support for $NEO, I'm simply not familiar with it nor any of its development libraries. I would include this but maybe on a specific list for each blockchain out there (ie. $EOS, etc). Not sure yet how it would be best to feature on README.

**Comment by vncoelho** [comment]
I do know, check it out where is the best place for including these information, about the integration with Smart Contracts.

If a dedicated slot/page is created would be better and we could describe the possibilities with more carefull. 

Whats do you suggest?

**Comment by santisiri** [comment]
Maybe it makes sense to have a specific section related to how we branch the project for specific cryptocurrencies. We'll think about it. In the meantime I can't merge this as it is, but happy to consider any suggestions considering what we discussed.

**Comment by vncoelho** [comment]
@santisiri, then, what are the next steps?

Update the ROADMAP and create a specific folder with a brief description .MD?

**Pull request closed without merging**
